version: "3.2"

services:
  coin_app:
    image: coin-app-service
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python3 app/main.py
    volumes:
      - ../:/usr/src/app/
    ports:
      - 8081:5000
      - 10008:10008
    environment:
      - WEB_APP_VERSION=1.0.0
      - WEB_APP_TITLE=coin-app
      - WEB_APP_DESCRIPTION=App service for Technical Test
      - POSTGRES_DATABASE_URL=postgresql://postgres:postgres@db:5432/db_dev'
      - ENVIRONMENT=dev
      - DEFAULT_EXPIRE_TIME=3600
    networks:
      - coin

  db:
    image: coin-db
    build:
      context: ../db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_coin:/var/lib/postgresql/data
    networks:
      - coin

volumes:
  db_coin:
    external: true

networks:
  coin:
    external: true
